---
- name: creating an instance in AWS using default VPC and Security Group
  hosts: localhost
  vars:
    instance_info:
      - name: "test server"
        image: "ami-835b4efa" # Ubuntu 14.04
        group_id: '<security-group'
        region: 'us-west-2'
        instance_type: 't2.micro'
        #platform: 'test'
        key_name: '<key-name>'
        vpc_subnet_id: 'subnet-8f4e82ea'
  tasks:
    - name: Creating the instance
      ec2:
        group_id: "{{ item.group_id }}"
        region: "{{ item.region }}"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        image: '{{ item.image }}'
        instance_type: "{{ item.instance_type }}"
        key_name: "{{ item.key_name }}"
        state: present
        assign_public_ip: true
        instance_tags:
          Name: Project_test
        vpc_subnet_id: 'subnet-4a07823d'
        wait: yes
      register: ec2
      with_items: instance_info

    - name: Wait for SSH
      wait_for:
        host: "{{ item['instances'][0]['public_ip'] }}"
        port: 22
        delay: 10
        timeout: 180
        state: started
      with_items: ec2.results

    - name: Add hosts group temporary inventory group with pem path
      add_host:
        name: "{{ ec2.results[item.0]['instances'][0]['public_ip'] }}"
        groups: dynamic_hosts
        ansible_ssh_host: "{{ ec2.results[item.0]['instances'][0]['public_ip'] "
        ansible_ssh_private_key_file: 'key-name'
        ansible_ssh_user: ubuntu
        ec2_vars: "{{ ec2.results[item.0]['instances'][0] }}"
        ec2_instance_ids: "{{ ec2.results[item.0]['instance_ids'] }}"
      with_indexed_items: instance_info
- hosts: dynamic_hosts
  become: true
  remote_user: ubuntu
  roles:
  - ansible-role-java  




