---
- hosts: all
  tasks: 
    - ec2_vpc:
        state: present
        cidr_block: 10.3.0.0/16
        resource_tags: { "Environment":"Development" }
        region: ap-northeast-1
        state: present
        instance_tenancy: dedicated
