---
- name: Check if MySQL is already installed.
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes
  when: mysql_installed.stat.exists == false

- name: Ensure MySQL Python libraries are installed.
  apt: "name=python-mysqldb state=installed"

- name: Set up ansible facts based on OS (since mysql server 5.6 not present in ubuntu 16.04)
  set_fact: 
    mysql_packages: mysql-server
  when: ansible_lsb['release'] | int  >= 16

- name: Ensure MySQL packages are installed.
  apt: "name={{ item }} state=installed"
  with_items: "{{ mysql_packages }}"
  register: deb_mysql_install_packages

- name: Delete innodb log files created by apt package after initial install.
  file: path={{ mysql_datadir }}/{{item}} state=absent
  with_items:
          - "ib_logfile0"
          - "ib_logfile1"
  when: mysql_installed.stat.exists == false

- name: Print mysql service status
  shell: service mysql status
  ignore_errors: true

